.TH "src/core/common.cpp" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/core/common.cpp \- Core common utils for libnumerixpp\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcredits\fP (void)"
.br
.RI "print credits "
.in -1c
.SH "Detailed Description"
.PP 
Core common utils for libnumerixpp\&. 


.PP
\fBAuthors\fP
.RS 4
alxvdev 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
