.TH "include/libnumerixpp/physics/core.hpp" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libnumerixpp/physics/core.hpp \- Core utils for physics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBphysics\fP"
.br
.RI "Basic physics utils\&. "
.in -1c
.SH "Detailed Description"
.PP 
Core utils for physics\&. 


.PP
\fBAuthors\fP
.RS 4
alxvdev 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
