.TH "include/libnumerixpp/physics/kinematics.hpp" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libnumerixpp/physics/kinematics.hpp \- Physics utils for kinematics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBphysics\fP"
.br
.RI "Basic physics utils\&. "
.ti -1c
.RI "namespace \fBphysics::kinematics\fP"
.br
.RI "Namespace of kinematics (physics) "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "double \fBphysics::kinematics::calculatePath\fP (double speed, double time)"
.br
.RI "Calculates the path\&. "
.ti -1c
.RI "double \fBphysics::kinematics::calculateSpeed\fP (double path, double time)"
.br
.RI "Calculates the speed\&. "
.ti -1c
.RI "double \fBphysics::kinematics::calculateTime\fP (double path, double speed)"
.br
.RI "Calculates the time\&. "
.ti -1c
.RI "double \fBphysics::kinematics::calculateFinalVelocity\fP (double initial_velocity, double acceleration, double time)"
.br
.RI "Calculates the final velocity\&. "
.ti -1c
.RI "double \fBphysics::kinematics::calculateFinalPosition\fP (double initial_position, double initial_velocity, double acceleration, double time)"
.br
.RI "Calculates the final position\&. "
.in -1c
.SH "Detailed Description"
.PP 
Physics utils for kinematics\&. 


.PP
\fBAuthors\fP
.RS 4
alxvdev 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
