.TH "src/libnumerixpp.cpp" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/libnumerixpp.cpp \- A Powerful C++ Library for High-Performance Numerical Computing\&.  

.SH SYNOPSIS
.br
.PP
\fR#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprintln\fP (std::string string)"
.br
.RI "Print string with new line\&. "
.in -1c
.SH "Detailed Description"
.PP 
A Powerful C++ Library for High-Performance Numerical Computing\&. 


.PP
\fBVersion\fP
.RS 4
0\&.1\&.0 
.RE
.PP
\fBDate\fP
.RS 4
2024-09-21 
.RE
.PP
\fBAuthors\fP
.RS 4
alxvdev 
.RE
.PP
\fBCopyright\fP
.RS 4
Apache 2\&.0 License 
.RE
.PP

.SH "Function Documentation"
.PP 
.SS "void println (std::string string)"

.PP
Print string with new line\&. 
.PP
\fBParameters\fP
.RS 4
\fIstring\fP The string 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
