.TH "mathematics::statistics" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mathematics::statistics \- Statistics namespace\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Statistics namespace\&. 


.PP
.nf


.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
