.TH "include/libnumerixpp/mathematics/statistics.hpp" 3 "Version 0.1.0" "libnumerixpp" \" -*- nroff -*-
.ad l
.nh
.SH NAME
include/libnumerixpp/mathematics/statistics.hpp \- Mathematics utils for statistics\&.  

.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBmathematics\fP"
.br
.RI "Basic mathematics utils\&. "
.ti -1c
.RI "namespace \fBmathematics::statistics\fP"
.br
.RI "Statistics namespace\&. "
.in -1c
.SH "Detailed Description"
.PP 
Mathematics utils for statistics\&. 


.PP
\fBAuthors\fP
.RS 4
alxvdev 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for libnumerixpp from the source code\&.
